/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ModelJNI */

#ifndef _Included_ModelJNI
#define _Included_ModelJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ModelJNI
 * Method:    floatArrayMethod
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ModelJNI_floatArrayMethod
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
